-- ════════════════════════════════════════════════════════════════
-- SOLO OS — SEED: Achievements (107 definitions)
-- AUTO-GENERATED from src/constants/achievements.ts by generate.ts.
-- Do not edit by hand.
-- ════════════════════════════════════════════════════════════════

insert into achievements (key, name, description, rarity, metric, threshold, unlocks_title_key, coin_reward, sort_order) values
  ('first_signal','FIRST SIGNAL','Complete your first mission.','COMMON','missions_completed',1,'the_initiate',20,1),
  ('system_link','SYSTEM LINK','Use SOLO OS for 7 days.','COMMON','active_days',7,null,30,2),
  ('system_bond','SYSTEM BOND','Use SOLO OS for 30 days.','RARE','active_days',30,null,60,3),
  ('system_fusion','SYSTEM FUSION','Use SOLO OS for 100 days.','EPIC','active_days',100,null,120,4),
  ('system_eternal','SYSTEM ETERNAL','Use SOLO OS for 365 days.','MYTHIC','active_days',365,null,500,5),
  ('awakening','AWAKENING','Reach Level 5.','COMMON','level',5,null,40,6),
  ('ascension_begins','ASCENSION BEGINS','Reach Level 10.','RARE','level',10,null,80,7),
  ('vanguard_rise','VANGUARD RISE','Reach Level 21.','RARE','level',21,null,120,8),
  ('ascendant_path','ASCENDANT PATH','Reach Level 36.','EPIC','level',36,'the_ascendant',180,9),
  ('elite_status','ELITE STATUS','Reach Level 51.','EPIC','level',51,null,250,10),
  ('apex_reached','APEX REACHED','Reach Level 66.','LEGENDARY','level',66,null,350,11),
  ('transcendence','TRANSCENDENCE','Reach Level 81.','LEGENDARY','level',81,null,450,12),
  ('paragon','PARAGON','Reach Level 91.','MYTHIC','level',91,null,600,13),
  ('sovereign','SOVEREIGN','Reach Level 100.','MYTHIC','level',100,'the_sovereign',1000,14),
  ('mission_10','OPERATIVE','Complete 10 missions.','COMMON','missions_completed',10,null,30,15),
  ('mission_50','FIELD AGENT','Complete 50 missions.','RARE','missions_completed',50,null,60,16),
  ('mission_100','VETERAN','Complete 100 missions.','RARE','missions_completed',100,null,100,17),
  ('mission_500','MISSION MASTER','Complete 500 missions.','EPIC','missions_completed',500,null,250,18),
  ('mission_1000','RELENTLESS','Complete 1000 missions.','LEGENDARY','missions_completed',1000,null,500,19),
  ('no_excuses','NO EXCUSES','Complete all core missions for 7 days.','EPIC','perfect_days',7,null,150,20),
  ('flawless_month','FLAWLESS PROTOCOL','Complete all core missions for 30 days.','MYTHIC','perfect_days',30,null,600,21),
  ('focus_first','FIRST FOCUS','Complete your first focus session.','COMMON','focus_sessions',1,null,15,22),
  ('focus_10','FOCUSED MIND','Complete 10 focus sessions.','COMMON','focus_sessions',10,null,30,23),
  ('deep_diver','DEEP DIVER','Complete 50 focus sessions.','RARE','focus_sessions',50,'focus_hunter',80,24),
  ('focus_200','DEEP WORK MASTER','Complete 200 focus sessions.','EPIC','focus_sessions',200,'deep_work_master',200,25),
  ('focus_hours_100','CENTURION OF FOCUS','Accumulate 100 hours of focus.','EPIC','focus_hours',100,null,220,26),
  ('focus_hours_500','MIND FORTRESS','Accumulate 500 hours of focus.','LEGENDARY','focus_hours',500,null,450,27),
  ('dsa_10','PROBLEM SOLVER','Solve 10 DSA problems.','COMMON','dsa_problems',10,null,25,28),
  ('algorithm_hunter','ALGORITHM HUNTER','Solve 100 DSA problems.','RARE','dsa_problems',100,'algorithm_hunter',100,29),
  ('algorithm_slayer','ALGORITHM SLAYER','Solve 500 DSA problems.','LEGENDARY','dsa_problems',500,null,400,30),
  ('algorithm_god','ALGORITHM ASCENDANT','Solve 1000 DSA problems.','MYTHIC','dsa_problems',1000,null,800,31),
  ('workout_first','FIRST FORGE','Complete your first workout.','COMMON','workouts',1,null,15,32),
  ('workout_25','STEEL FORMING','Complete 25 workouts.','COMMON','workouts',25,null,40,33),
  ('iron_will','IRON WILL','Complete 100 workouts.','EPIC','workouts',100,'iron_mind',180,34),
  ('iron_body','IRON BODY','Complete 300 workouts.','LEGENDARY','workouts',300,null,400,35),
  ('run_50k','DISTANCE RUNNER','Run 50 km total.','RARE','run_distance_km',50,null,80,36),
  ('run_250k','MARATHON SPIRIT','Run 250 km total.','EPIC','run_distance_km',250,null,220,37),
  ('silence_7','QUIET MIND','Control Reels and Shorts for 7 days.','COMMON','digital_silence_days',7,null,40,38),
  ('digital_silence','DIGITAL SILENCE','Control Reels and Shorts for 30 days.','EPIC','digital_silence_days',30,null,160,39),
  ('silence_100','THE UNPLUGGED','Control Reels and Shorts for 100 days.','LEGENDARY','digital_silence_days',100,null,400,40),
  ('gate_first','GATE INITIATE','Complete your first GATE study session.','COMMON','gate_sessions',1,null,20,41),
  ('gate_hours_50','GATE SCHOLAR','Accumulate 50 hours of GATE study.','RARE','gate_hours',50,null,100,42),
  ('gate_hours_200','GATE CHALLENGER','Complete 500 GATE PYQs.','EPIC','gate_pyqs',500,null,250,43),
  ('gate_hours_500','GATE CONQUEROR','Accumulate 500 hours of GATE study.','LEGENDARY','gate_hours',500,null,500,44),
  ('streak_wake_7','DAWNBREAKER','Hold a 7-day wake streak.','COMMON','max_wake_streak',7,null,40,45),
  ('streak_wake_30','MASTER OF MORNINGS','Hold a 30-day wake streak.','EPIC','max_wake_streak',30,null,160,46),
  ('streak_workout_30','UNBROKEN BODY','Hold a 30-day workout streak.','EPIC','max_workout_streak',30,null,160,47),
  ('streak_dsa_30','DAILY SOLVER','Hold a 30-day DSA streak.','EPIC','max_dsa_streak',30,null,160,48),
  ('streak_routine_30','THE DISCIPLINED','Hold a 30-day routine streak.','EPIC','max_routine_streak',30,'the_disciplined',160,49),
  ('streak_100','CENTURY OF WILL','Hold any streak for 100 days.','LEGENDARY','max_any_streak',100,'the_consistent',400,50),
  ('recovery_first','FIRST RETURN','Complete your first recovery protocol.','COMMON','recoveries_completed',1,null,20,51),
  ('recovery_10','THE RESILIENT','Complete 10 recovery protocols.','RARE','recoveries_completed',10,null,80,52),
  ('the_unyielding','THE UNYIELDING','Recover from 25 failed days and return to the System.','LEGENDARY','recoveries_completed',25,'the_unyielding',350,53),
  ('urge_resist_50','SHADOW WARDEN','Resist 50 urges.','EPIC','urges_resisted',50,null,180,54),
  ('urge_resist_200','SHADOW SOVEREIGN','Resist 200 urges.','LEGENDARY','urges_resisted',200,null,400,55),
  ('boss_first','GIANT SLAYER','Defeat your first boss.','RARE','bosses_defeated',1,null,100,56),
  ('boss_3','TRIAL BREAKER','Defeat 3 bosses.','EPIC','bosses_defeated',3,null,220,57),
  ('boss_all','NEMESIS ENDER','Defeat all initial bosses.','LEGENDARY','bosses_defeated',6,null,500,58),
  ('xp_10k','ENERGY RISING','Earn 10,000 lifetime XP.','RARE','lifetime_xp',10000,null,80,59),
  ('xp_100k','POWER SURGE','Earn 100,000 lifetime XP.','EPIC','lifetime_xp',100000,null,250,60),
  ('xp_1m','BOUNDLESS','Earn 1,000,000 lifetime XP.','MYTHIC','lifetime_xp',1000000,null,1000,61),
  ('coins_1k','SAVER','Earn 1,000 lifetime coins.','COMMON','lifetime_coins',1000,null,30,62),
  ('coins_10k','TREASURER','Earn 10,000 lifetime coins.','EPIC','lifetime_coins',10000,null,200,63),
  ('study_hours_25','SCHOLAR I','Accumulate total study hours: 25.','COMMON','total_study_hours',25,null,30,64),
  ('study_hours_100','SCHOLAR II','Accumulate total study hours: 100.','RARE','total_study_hours',100,null,70,65),
  ('study_hours_300','SCHOLAR III','Accumulate total study hours: 300.','EPIC','total_study_hours',300,null,160,66),
  ('study_hours_750','SCHOLAR IV','Accumulate total study hours: 750.','LEGENDARY','total_study_hours',750,null,350,67),
  ('study_hours_1500','SCHOLAR V','Accumulate total study hours: 1500.','MYTHIC','total_study_hours',1500,null,700,68),
  ('deepwork_days_10','FOCUSED I','Log deep work on separate days: 10.','COMMON','deep_work_days',10,null,30,69),
  ('deepwork_days_50','FOCUSED II','Log deep work on separate days: 50.','RARE','deep_work_days',50,null,80,70),
  ('deepwork_days_150','FOCUSED III','Log deep work on separate days: 150.','EPIC','deep_work_days',150,null,180,71),
  ('deepwork_days_365','FOCUSED IV','Log deep work on separate days: 365.','LEGENDARY','deep_work_days',365,null,400,72),
  ('aiml_hours_25','NEURAL I','Accumulate AI/ML hours: 25.','COMMON','aiml_hours',25,null,30,73),
  ('aiml_hours_100','NEURAL II','Accumulate AI/ML hours: 100.','RARE','aiml_hours',100,null,80,74),
  ('aiml_hours_300','NEURAL III','Accumulate AI/ML hours: 300.','EPIC','aiml_hours',300,null,180,75),
  ('aiml_hours_600','NEURAL IV','Accumulate AI/ML hours: 600.','LEGENDARY','aiml_hours',600,null,380,76),
  ('fullstack_hours_25','BUILDER I','Accumulate full-stack hours: 25.','COMMON','fullstack_hours',25,null,30,77),
  ('fullstack_hours_100','BUILDER II','Accumulate full-stack hours: 100.','RARE','fullstack_hours',100,null,80,78),
  ('fullstack_hours_300','BUILDER III','Accumulate full-stack hours: 300.','EPIC','fullstack_hours',300,null,180,79),
  ('fullstack_hours_600','BUILDER IV','Accumulate full-stack hours: 600.','LEGENDARY','fullstack_hours',600,null,380,80),
  ('sysdesign_hours_20','ARCHITECT I','Accumulate system design hours: 20.','COMMON','sysdesign_hours',20,null,30,81),
  ('sysdesign_hours_80','ARCHITECT II','Accumulate system design hours: 80.','RARE','sysdesign_hours',80,null,80,82),
  ('sysdesign_hours_200','ARCHITECT III','Accumulate system design hours: 200.','EPIC','sysdesign_hours',200,null,180,83),
  ('datasci_hours_20','ANALYST I','Accumulate data science hours: 20.','COMMON','datasci_hours',20,null,30,84),
  ('datasci_hours_80','ANALYST II','Accumulate data science hours: 80.','RARE','datasci_hours',80,null,80,85),
  ('datasci_hours_200','ANALYST III','Accumulate data science hours: 200.','EPIC','datasci_hours',200,null,180,86),
  ('coins_spent_500','INDULGENT I','Spend lifetime coins on rewards: 500.','COMMON','coins_spent',500,null,0,87),
  ('coins_spent_5000','INDULGENT II','Spend lifetime coins on rewards: 5000.','RARE','coins_spent',5000,null,0,88),
  ('coins_spent_20000','INDULGENT III','Spend lifetime coins on rewards: 20000.','EPIC','coins_spent',20000,null,0,89),
  ('campaign_stages_1','PATHFINDER I','Master campaign stages: 1.','COMMON','campaign_stages_mastered',1,null,30,90),
  ('campaign_stages_10','PATHFINDER II','Master campaign stages: 10.','RARE','campaign_stages_mastered',10,null,90,91),
  ('campaign_stages_30','PATHFINDER III','Master campaign stages: 30.','EPIC','campaign_stages_mastered',30,null,220,92),
  ('campaign_stages_60','PATHFINDER IV','Master campaign stages: 60.','LEGENDARY','campaign_stages_mastered',60,null,500,93),
  ('boss_damage_500','DESTROYER I','Deal total boss damage: 500.','COMMON','total_boss_damage',500,null,30,94),
  ('boss_damage_5000','DESTROYER II','Deal total boss damage: 5000.','RARE','total_boss_damage',5000,null,90,95),
  ('boss_damage_25000','DESTROYER III','Deal total boss damage: 25000.','EPIC','total_boss_damage',25000,null,240,96),
  ('early_days_10','EARLY RISER I','Wake before target on days: 10.','COMMON','wake_success_days',10,null,30,97),
  ('early_days_50','EARLY RISER II','Wake before target on days: 50.','RARE','wake_success_days',50,null,90,98),
  ('early_days_150','EARLY RISER III','Wake before target on days: 150.','EPIC','wake_success_days',150,null,200,99),
  ('early_days_365','EARLY RISER IV','Wake before target on days: 365.','LEGENDARY','wake_success_days',365,null,450,100),
  ('shadow_control_days_7','WARDEN I','Maintain shadow control on days: 7.','COMMON','shadow_control_days',7,null,30,101),
  ('shadow_control_days_30','WARDEN II','Maintain shadow control on days: 30.','RARE','shadow_control_days',30,null,100,102),
  ('shadow_control_days_90','WARDEN III','Maintain shadow control on days: 90.','EPIC','shadow_control_days',90,null,240,103),
  ('shadow_control_days_180','WARDEN IV','Maintain shadow control on days: 180.','LEGENDARY','shadow_control_days',180,null,480,104),
  ('reward_purchases_1','SELF-KEEPER I','Redeem rewards from the vault: 1.','COMMON','rewards_purchased',1,null,0,105),
  ('reward_purchases_10','SELF-KEEPER II','Redeem rewards from the vault: 10.','RARE','rewards_purchased',10,null,0,106),
  ('reward_purchases_50','SELF-KEEPER III','Redeem rewards from the vault: 50.','EPIC','rewards_purchased',50,null,0,107)
on conflict (key) do update set
  name=excluded.name, description=excluded.description, rarity=excluded.rarity,
  metric=excluded.metric, threshold=excluded.threshold,
  unlocks_title_key=excluded.unlocks_title_key, coin_reward=excluded.coin_reward,
  sort_order=excluded.sort_order;
